### ISSUE TITLE
COVE Validation check: Check that dates of death of natural persons are sane

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/lib-cove-bods#49] opened 2020-01-16 15:41 UTC
Check that dates of death of natural persons are sane. As a start I'll suggest:

- no one has a date of death in the future
- no one has a date of death more than 120 years after their date of birth

which are largely in keeping with the checks that we have implemented for date of birth.

@odscjames we added a similar set of checks for date of birth. It looks as though we made [changes to the code here for the general case](https://github.com/openownership/lib-cove-bods/pull/9/commits/e92c0950b70ebcba30d88490797c7c892bc95abe) and then added configuration to the [cove-bods repo](https://github.com/openownership/cove-bods/pull/29/files). Is it ok for me to raise the whole of the issue here, or should I split it into the two issues?

**Comment by stevenday** [comment] 2020-09-09 09:44
Closing as a dupe of #59 which seems more complete

**Closed by stevenday** 2020-09-09 09:44 UTC
Labels: test
