### ISSUE TITLE
Unhelpful validation error message

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#64] opened 2020-11-24 15:12 UTC
(I hope this is the right repo for this issue.) Try running this json through the [data review tool](https://datareview.openownership.org):

`[
  {
  "annotations": [
     {
        "motivation": "correcting"
     }
  ],
    "addresses": [
      {
        "country": "EE", 
        "type": "residence"
      }
    ], 
    "birthDate": "1985-02", 
    "identifiers": [
      {
        "id": "280871-*****", 
        "schemeName": "GTR-PASSPORT"
      }
    ], 
    "isComponent": false, 
    "names": [
      {
        "familyName": "Nonymou", 
        "fullName": "A Nonymous", 
        "givenName": "A", 
        "type": "individual"
      }
    ], 
    "nationalities": [
      {
        "code": "GB"
      }
    ], 
    "personType": "knownPerson", 
    "publicationDetails": {
      "bodsVersion": "0.2", 
      "license": "http://creativecommons.org/publicdomain/zero/1.0/", 
      "publicationDate": "2020-11-10", 
      "publisher": {
        "name": "Test Register", 
        "url": "http://www.test.com"
      }
    }, 
    "source": {
      "assertedBy": [
        {
          "name": "Me"
        }
      ], 
      "type": [
        "selfDeclaration", 
        "officialRegister"
      ]
    }, 
    "statementDate": "2020-10-30", 
    "statementID": "d5764567474-d2a5-4e89-be41-614crgdtgsdgsgsfg", 
    "statementType": "personStatement"
  }
]`

It throws the error: '{'motivation': 'correcting'} is not valid under any of the given schemas'. This does not help with troubleshooting. A better message would be:

'{'motivation': 'correcting'} is not valid according to the BODS schema. See https://github.com/openownership/data-standard/tree/master/schema.

Or if we could link to the relevant place in the BODS schema that would be even better. (In this case:

https://github.com/openownership/data-standard/blob/master/schema/components.json#L394, OR

https://github.com/openownership/data-standard/blob/7693b43c7d506106196bd83c7cd440e57236341d/schema/components.json#L329)

**Comment by kd-ods** [comment] 2021-08-17 13:44
To clarify the above. Because of the json schema logic, the user is told "{'motivation': 'correcting'} is not valid under any of the given schemas", rather than the more useful information: statementPointerTarget is a required property of an annotation.

So, if this isn't fixable with a change to the json schema logic, then pointing to the relevant point in the schema is the next best option.

**Comment by kd-ods** [comment] 2021-09-20 10:03
Just noticed that the existing schema logic also causes/relates to this issue: https://github.com/openownership/data-standard/issues/333

**Comment by odscjames** [comment] 2021-09-21 12:58
This is caused by use of "anyOf" - if the data does not match the JSON Schema validator doesn't know which one of the onyOf clauses to use, hence the unhelpful error message. If we could remove the "anyOf" that would be a simple fix, but having just had a quick look I'm not sure we can. We fixed a similar problem with regards to better errors with the 3 statement types, but this might be harder to solve as for that one we could use the "type" key to choose the correct schema and this time there is no such key.

**Comment by rhiaro** [comment] 2021-10-29 19:04
I don't like using schema properties to provide config options the validator, which `oneOfEnumSelectorField` is doing. It's not Data, as in it isn't something someone publishing BODS would fill in a value for. It would be out of place to show up in the schema reference or schema browser documentation. It's not something an end user of the data - either publisher or consumer - should have to think about.

If there's a better way to pass this information to the validator (specifically cove, as any other hypothetical BODS validator may do things a different way) we should look at that instead of adding to the schema in this case.

**Comment by odscjames** [comment] 2021-11-02 11:12
Discussed with @kd-ods this morning - we'll put in schema for now.

**Comment by odscjames** [comment] 2021-11-10 10:18
This is not released yet. 2 things need to happen for this to be released:

* Cove needs to start using 0.27.0 of Libcove - this will happen at some point anyway.
* The next version of BODS schema needs to be released with the change.

Discussed with @kd-ods this morning: given the size of problem we are happy to wait for these and thus I am now closing this.

**Closed by odscjames** 2021-11-10 10:18 UTC
